graph.InsertEdge(Loc1, Loc6, h(Loc1,Loc6))
graph.InsertEdge(Loc2, Loc3, h(Loc2,Loc3))
graph.InsertEdge(Loc2, Loc7, h(Loc2,Loc7))
graph.InsertEdge(Loc2, Loc8, h(Loc2,Loc8))
graph.InsertEdge(Loc3, Loc4, h(Loc3,Loc4))
graph.InsertEdge(Loc4, Loc9, h(Loc4,Loc9))
graph.InsertEdge(Loc5, Loc6, h(Loc5,Loc6))
graph.InsertEdge(Loc5, Loc9, h(Loc5,Loc9))
graph.InsertEdge(Loc6, Loc7, h(Loc6,Loc7))
graph.InsertEdge(Loc7, Loc8, h(Loc7,Loc8))
graph.InsertEdge(Loc9, Loc10, h(Loc9,Loc10))

graph.InsertEdge(Loc, Loc, h(Loc,Loc))
graph.InsertEdge(Loc, Loc, h(Loc,Loc))
graph.InsertEdge(Loc, Loc, h(Loc,Loc))
